"""Tests for freddie/lgd.py -- SFLLD realized-loss workout LGD (rung 3).

Speed note: production `freddie/fit_lgd.py::main()` builds the LGD sample
over ALL 17 vintages' had_d90_event loans (44,593 D90 events), which re-reads
raw SFLLD servicing zips for the NaN-zero_balance_code subset (several
minutes -- see fit_lgd.py's module docstring). These tests instead exercise
the SAME functions (`partition_outcomes`, `resolve_reverted_status`,
`build_lgd_sample`, `fit_cure_model`, `fit_severity_model`, `fit_lgd_models`,
`predict_components`) on a single small vintage (2007: 50,000 loans, 8,130
had_d90_event -- chosen, like tests/test_freddie_ingest.py's TRACE_YEAR, for
having real liquidations AND every zero_balance_code this module branches on:
01/16 cure, 02/03/09 liquidation, 15 both-ways NPL-sale split, 96 unresolved,
plus a NaN-zero_balance_code reverted-status subset) -- no mocking of the
outcome-partition or sign-convention logic, just a smaller real slice of it.

The sign-convention fixture loans below are hand-traced by direct zipfile
inspection against freddie/ingest.read_svcg_vintage's raw output (same method
as tests/test_freddie_ingest.py's TRACE_PREPAY_LOAN / TRACE_CURE_LOAN), not
generated by the module under test -- an independent check, not a
tautology.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from freddie import fit_lgd as fl
from freddie import ingest, lgd

TRACE_YEAR = 2007  # small vintage with real liquidations + every zb code branch


def _require_cache(path):
    if not path.exists():
        pytest.skip(f"cache not built yet ({path}) -- run the freddie ingestion pipeline first")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def orig_subset() -> pd.DataFrame:
    _require_cache(fl.ORIG_PATH)
    orig = pd.read_parquet(fl.ORIG_PATH)
    return orig.loc[orig["vintage"] == TRACE_YEAR].reset_index(drop=True)


@pytest.fixture(scope="module")
def panel_d90_subset() -> pd.DataFrame:
    _require_cache(fl.PANEL_PATH)
    # Predicate-pushdown chunk read (mirrors freddie/fit_hazard.py's
    # per-vintage pattern) -- never materializes the full 39.5M-row panel.
    return pd.read_parquet(
        fl.PANEL_PATH,
        columns=lgd.PANEL_MONTHLY_REQUIRED_COLS,
        filters=[("vintage", "==", TRACE_YEAR), ("d90_event", "==", 1)],
    ).reset_index(drop=True)


@pytest.fixture(scope="module")
def sample(orig_subset, panel_d90_subset) -> pd.DataFrame:
    return lgd.build_lgd_sample(orig_subset, panel_d90_subset)


@pytest.fixture(scope="module")
def full_sample() -> pd.DataFrame:
    """The FULL 17-vintage, 44,593-loan production sample -- read from
    fit_lgd.py's cache (data/processed/freddie/lgd/lgd_sample.parquet),
    never rebuilt here (that re-reads all 17 raw zips, several minutes --
    see fit_lgd.py's module docstring). Used ONLY for the economic-sign-
    guard / population-aggregate tests below, which need enough liquidation
    volume and liq_year_bucket / era diversity for the fitted LTV
    coefficients to be stable -- the single-vintage `sample` fixture above
    (8,130 loans, one origination cohort) is authoritative for outcome-
    partition and sign-convention logic, but too thin for the severity
    stage's `ltv10` coefficient to reliably reproduce its population-level
    sign (a legitimate small-sample artifact: fit_lgd_models's own economic-
    sign guard correctly REJECTS the single-vintage fit, exactly as
    designed -- see freddie/lgd.py's module docstring, "fit_lgd_models
    raises AssertionError if either economic sign is violated")."""
    _require_cache(fl.SAMPLE_CACHE_PATH)
    return pd.read_parquet(fl.SAMPLE_CACHE_PATH)


@pytest.fixture(scope="module")
def full_models(full_sample) -> lgd.LgdModels:
    return lgd.fit_lgd_models(full_sample, split="train")


@pytest.fixture(scope="module")
def cure_model(sample):
    """Fit on ALL of the small vintage's resolved rows (split=None) -- a
    single vintage doesn't have enough post-2019 OOT rows to fit train-only
    the way fit_lgd.py's full-population run does."""
    return lgd.fit_cure_model(sample, split=None)


@pytest.fixture(scope="module")
def severity_model_and_meta(sample):
    return lgd.fit_severity_model(sample, split=None)


# ---------------------------------------------------------------------------
# 1. Sign convention -- hand-traced fixture loans (raw zip, independent of
#    the module under test)
# ---------------------------------------------------------------------------
# F05Q10000744 (2005 vintage), terminal row 2011-10, zero_balance_code=="09"
# (REO disposition). Hand-traced via freddie.ingest.read_svcg_vintage(2005)
# and cross-checked against a direct raw-zip read (orchestrator transcript).
TRACE_LOAN_A_VINTAGE = 2005
TRACE_LOAN_A_ID = "F05Q10000744"
TRACE_LOAN_A = {
    "net_sale_proceeds": 3036.47,
    "mi_recoveries": 7521.0698,
    "non_mi_recoveries": 704.09998,
    "total_expenses": -6682.2798,          # already NEGATIVE on the raw tape
    "zero_balance_removal_upb": 22791.15,
    "delinquent_accrued_interest": 1783.88,
    "actual_loss_calculation": -19995.669921875,
}


def test_sign_convention_fixture_loan():
    """`actual_loss_calculation` reconciles (sub-dollar rounding) to
    net_sale_proceeds + mi_recoveries + non_mi_recoveries + total_expenses
    - zero_balance_removal_upb - delinquent_accrued_interest (lgd.py's
    module docstring). This is the empirical basis for realized_loss = -
    actual_loss_calculation -- checked against the raw tape, not assumed."""
    row = TRACE_LOAN_A
    computed = (
        row["net_sale_proceeds"] + row["mi_recoveries"] + row["non_mi_recoveries"]
        + row["total_expenses"] - row["zero_balance_removal_upb"] - row["delinquent_accrued_interest"]
    )
    assert computed == pytest.approx(row["actual_loss_calculation"], abs=1.0)
    # A shortfall (removal UPB + accrued interest not fully recovered by
    # proceeds/recoveries net of costs) makes actual_loss_calculation
    # NEGATIVE; realized_loss = -actual_loss_calculation must therefore be
    # POSITIVE (an economic loss, the common-sense direction).
    realized_loss = -row["actual_loss_calculation"]
    assert realized_loss > 0


def test_sign_convention_fixture_loan_traced_live():
    """Same fixture loan, re-traced live from the raw SFLLD zip (not the
    hardcoded numbers above) -- catches drift if ingest.py's parsing ever
    changes the reported values."""
    svcg = ingest.read_svcg_vintage(TRACE_LOAN_A_VINTAGE)
    sub = svcg.loc[svcg["loan_sequence_number"] == TRACE_LOAN_A_ID]
    term = sub.loc[sub["zero_balance_code"].notna()]
    assert not term.empty, f"{TRACE_LOAN_A_ID} has no terminal zero-balance row in {TRACE_LOAN_A_VINTAGE}"
    r = term.iloc[-1]
    assert str(r["zero_balance_code"]) == "09"
    computed = (
        float(r["net_sale_proceeds"]) + float(r["mi_recoveries"]) + float(r["non_mi_recoveries"])
        + float(r["total_expenses"]) - float(r["zero_balance_removal_upb"])
        - float(r["delinquent_accrued_interest"])
    )
    assert computed == pytest.approx(float(r["actual_loss_calculation"]), abs=1.0)
    assert float(r["actual_loss_calculation"]) == pytest.approx(
        TRACE_LOAN_A["actual_loss_calculation"], abs=1.0)


def test_sign_convention_holds_across_sample(sample):
    """Population-level lock (not just the one hand-traced loan): every
    liquidation row's realized_loss is the negation of the raw
    actual_loss_calculation column, and total_expenses (the sub-component
    Freddie already reports negative) never flips positive on a row with a
    populated loss field -- the sign discipline documented in lgd.py's
    module docstring holds across the whole small-vintage sample, not just
    the single fixture loan."""
    liq = sample.loc[sample["has_loss_data"]]
    assert len(liq) > 0
    pd.testing.assert_series_equal(
        liq["realized_loss"], -liq["actual_loss_calculation"],
        check_names=False,
    )


# ---------------------------------------------------------------------------
# 2. Outcome partition -- exhaustive + disjoint
# ---------------------------------------------------------------------------
def test_partition_exhaustive_no_nulls(sample):
    assert sample["lgd_outcome"].notna().all()


def test_partition_only_three_labels(sample):
    assert set(sample["lgd_outcome"].cat.categories) >= set(sample["lgd_outcome"].unique())
    assert set(sample["lgd_outcome"].dropna().unique()) <= {"cure", "liquidation", "unresolved"}


def test_partition_disjoint_by_construction(sample):
    """Each D90 loan appears exactly once in the sample (one row per loan,
    from build_lgd_sample's one_to_one merge validation) with exactly one
    lgd_outcome label -- disjointness is structural, not just untested."""
    assert sample["loan_sequence_number"].is_unique


def test_cure_zb_codes_labeled_cure(sample):
    cure_rows = sample.loc[sample["zero_balance_code"].isin(lgd.CURE_ZB_CODES)]
    if len(cure_rows):
        assert (cure_rows["lgd_outcome"] == "cure").all()


def test_liquidation_zb_codes_labeled_liquidation(sample):
    liq_rows = sample.loc[sample["zero_balance_code"].isin(lgd.LIQUIDATION_ZB_CODES)]
    if len(liq_rows):
        assert (liq_rows["lgd_outcome"] == "liquidation").all()


def test_code96_always_unresolved_and_no_loss_data(sample):
    """zero_balance_code == 96 (defect prior to disposition) must be
    unresolved AND must carry NO actual_loss_calculation (module docstring:
    100% NaN on this code -- whoever repurchased the loan bears the loss,
    not Freddie)."""
    code96 = sample.loc[sample["zero_balance_code"] == "96"]
    if len(code96):
        assert (code96["lgd_outcome"] == "unresolved").all()
        assert not code96["has_loss_data"].any()


def test_npl_sale_code15_split_by_loss_data(sample):
    """zero_balance_code == 15 (whole loan sale) is liquidation IFF it
    carries a populated actual_loss_calculation, unresolved otherwise --
    the documented correction versus lumping all of code 15 into
    unresolved (lgd.py's module docstring, outcome-partition section)."""
    code15 = sample.loc[sample["zero_balance_code"] == "15"]
    if len(code15) == 0:
        pytest.skip("no code-15 rows in this vintage's D90 sample")
    has_loss = code15["has_loss_data"]
    assert (code15.loc[has_loss, "lgd_outcome"] == "liquidation").all()
    assert (code15.loc[~has_loss, "lgd_outcome"] == "unresolved").all()


def test_code16_treated_as_cure_never_has_loss_data(sample):
    code16 = sample.loc[sample["zero_balance_code"] == "16"]
    if len(code16):
        assert (code16["lgd_outcome"] == "cure").all()
        assert not code16["has_loss_data"].any()


def test_nan_zb_reverted_rows_are_cure(sample, panel_d90_subset):
    """NaN-zero_balance_code loans that resolve_reverted_status finds
    reverted below 90 DPD (and not REO) by their last observed raw row must
    be labeled cure; the rest must be unresolved."""
    nan_zb = sample.loc[sample["zero_balance_code"].isna()]
    if nan_zb.empty:
        pytest.skip("no NaN-zero_balance_code D90 loans in this vintage")
    reverted = lgd.resolve_reverted_status(nan_zb)
    expect = np.where(reverted.reindex(nan_zb.index).to_numpy(), "cure", "unresolved")
    np.testing.assert_array_equal(nan_zb["lgd_outcome"].to_numpy(), expect)


def test_unclassified_zero_balance_code_raises():
    """partition_outcomes must fail loudly (not silently drop to NaN/
    'unresolved') on a zero_balance_code it doesn't recognize."""
    bad = pd.DataFrame({
        "zero_balance_code": pd.Series(["77"], dtype="object"),
        "actual_loss_calculation": [np.nan],
    })
    with pytest.raises(AssertionError):
        lgd.partition_outcomes(bad)


# ---------------------------------------------------------------------------
# 3. Resolved-only selection: unresolved loans never enter either fit stage
# ---------------------------------------------------------------------------
def test_cure_stage_excludes_unresolved(sample, cure_model):
    """fit_cure_model's fitted sample (via the model's exog) must contain
    zero unresolved-outcome rows."""
    fit_index = cure_model.model.data.frame.index
    fitted_outcomes = sample.loc[fit_index, "lgd_outcome"]
    assert not (fitted_outcomes == "unresolved").any()
    assert set(fitted_outcomes.unique()) <= {"cure", "liquidation"}


def test_severity_stage_excludes_unresolved_and_no_loss_data(sample, severity_model_and_meta):
    sev_res, _ = severity_model_and_meta
    fit_index = sev_res.model.data.frame.index
    fitted_rows = sample.loc[fit_index]
    assert (fitted_rows["lgd_outcome"] == "liquidation").all()
    assert fitted_rows["has_loss_data"].all()


def test_resolved_only_matches_dcr_convention(sample):
    """Same population fit_lgd_models trains on: cure + liquidation, minus
    unresolved -- mirrors DCR's "unresolved lgd_time is not a realised
    outcome" rule (engine/lgd.py, cited in lgd.py's module docstring)."""
    resolved = sample.loc[sample["lgd_outcome"] != "unresolved"]
    assert set(resolved["lgd_outcome"].unique()) <= {"cure", "liquidation"}
    assert len(resolved) < len(sample) or sample["lgd_outcome"].eq("unresolved").sum() == 0


# ---------------------------------------------------------------------------
# 4. Severity bounds after documented treatment
# ---------------------------------------------------------------------------
def test_severity_capped_in_bounds(sample):
    """sev_capped (severity.clip(0, SEV_CAP), what actually feeds the
    fractional-logit link) must lie in [0, SEV_CAP] -- never NaN/inf for
    rows with usable loss data."""
    liq = sample.loc[(sample["lgd_outcome"] == "liquidation") & sample["has_loss_data"]]
    if liq.empty:
        pytest.skip("no liquidation rows with loss data in this vintage")
    capped = liq["severity"].clip(lower=0.0, upper=lgd.SEV_CAP)
    assert np.isfinite(capped.to_numpy()).all()
    assert (capped >= 0.0).all()
    assert (capped <= lgd.SEV_CAP).all()


def test_raw_severity_can_exceed_bounds_but_is_finite(sample):
    """Unlike sev_capped, raw `severity` is DELIBERATELY not clipped (module
    docstring: the >1 / <0 tail is real, reported, never silently
    discarded) -- but it must still be finite, not NaN/inf, for every row
    with a populated loss field."""
    liq = sample.loc[(sample["lgd_outcome"] == "liquidation") & sample["has_loss_data"]]
    if liq.empty:
        pytest.skip("no liquidation rows with loss data in this vintage")
    assert np.isfinite(liq["severity"].to_numpy()).all()


def test_severity_is_nan_for_non_liquidation_or_no_loss_data(sample):
    """Rows without usable loss data must NOT carry a fabricated severity."""
    no_loss = sample.loc[~sample["has_loss_data"]]
    assert no_loss["actual_loss_calculation"].isna().all()


# ---------------------------------------------------------------------------
# 5. Economic sign assertions
#
# The cure-stage sign check (test_cure_falls_in_ltv) holds up fine on the
# single small vintage. The SEVERITY-stage LTV coefficient does not: fit on
# one origination cohort's ~4,200 liquidations, `ltv10`'s point estimate can
# legitimately flip sign (cohort-specific LTV/severity covariation, thin
# liq_year_bucket coverage within one vintage) -- fit_lgd_models's own
# economic-sign guard correctly RAISES on that fit rather than shipping a
# wrong-sign model (verified separately, see
# test_fit_lgd_models_thin_sample_can_legitimately_reject_wrong_sign below).
# The tests that need the sign to actually hold (and everything downstream
# of a successfully fitted LgdModels) therefore use `full_sample`/
# `full_models` -- the cached FULL 44,593-loan production sample, which is
# what fit_lgd.py actually ships and what the real ltv10 coefficients in
# outputs/freddie/lgd/lgd_report.md come from (cure -0.2475, severity
# +0.0307, both correctly signed).
# ---------------------------------------------------------------------------
def test_cure_falls_in_ltv(cure_model):
    assert cure_model.params["ltv10"] < 0


def test_fit_lgd_models_thin_sample_can_legitimately_reject_wrong_sign(sample):
    """Documents (rather than hides) the single-vintage severity sign flip:
    fit_lgd_models must raise AssertionError, not silently ship a model
    whose severity falls in LTV."""
    with pytest.raises(AssertionError, match="severity must RISE in updated LTV"):
        lgd.fit_lgd_models(sample, split=None)


def test_cure_falls_in_ltv_full_sample(full_models):
    assert full_models.cure_result.params["ltv10"] < 0


def test_severity_rises_in_ltv_full_sample(full_models):
    assert full_models.severity_result.params["ltv10"] > 0


def test_fit_lgd_models_end_to_end_sign_guard(full_models):
    """fit_lgd_models raises AssertionError if either economic sign is
    violated (lgd.py); on the full production sample (split="train",
    matching fit_lgd.py's own main()) it must fit cleanly and produce a
    well-formed LgdModels object."""
    models = full_models
    assert models.n_resolved > 0
    assert models.n_cure + models.n_liquidation == models.n_resolved
    assert 0.0 <= models.floor_mass <= 1.0
    assert models.excess_loading >= 0.0
    assert models.lgd_upper_bound == pytest.approx(models.sev_cap + models.excess_loading)


# ---------------------------------------------------------------------------
# 6. predict_components / predict_lgd contract
#
# predict_components must be scored on LIQUIDATION-outcome rows only (see
# its docstring): a cure row's disposition_type is a real, non-NaN value
# (prepaid_or_matured / rpl_securitization) but is a category the severity
# GLM never trained on, so it is EXCLUDED here explicitly, matching how
# freddie/fit_lgd.py's population_lgd_summary actually calls this function
# in production (never on the full resolved population).
# ---------------------------------------------------------------------------
def test_predict_components_bounded(full_sample, full_models):
    models = full_models
    scoring_cols = [
        "ltv10", "fico_s", "loan_age_at_default", "era", "property_state",
        "liq_year_bucket", "is_judicial", "disposition_type",
    ]
    df = full_sample[
        (full_sample["split"] == "train") & (full_sample["lgd_outcome"] == "liquidation")
    ].dropna(subset=scoring_cols)
    assert not df.empty
    out = lgd.predict_components(models, df)
    assert (out["lgd"] >= -1e-9).all()
    assert (out["lgd"] <= models.lgd_upper_bound + 1e-9).all()
    assert (out["p_cure"] >= 0.0).all() and (out["p_cure"] <= 1.0).all()
    lgd_np = lgd.predict_lgd(models, df)
    np.testing.assert_allclose(lgd_np, out["lgd"].to_numpy())


def test_predict_components_rejects_nan_covariates(full_sample, full_models):
    models = full_models
    scoring_cols = [
        "ltv10", "fico_s", "loan_age_at_default", "era", "property_state",
        "liq_year_bucket", "is_judicial", "disposition_type",
    ]
    df = full_sample[
        (full_sample["split"] == "train") & (full_sample["lgd_outcome"] == "liquidation")
    ].dropna(subset=scoring_cols).head(3).copy()
    assert not df.empty
    df.iloc[0, df.columns.get_loc("ltv10")] = np.nan
    with pytest.raises(ValueError):
        lgd.predict_components(models, df)


# ---------------------------------------------------------------------------
# 7. liq_year_bucket helper
# ---------------------------------------------------------------------------
def test_liq_year_bucket_covers_documented_ranges():
    years = pd.Series([2006, 2008, 2011, 2015, 2018, 2022])
    out = lgd.liq_year_bucket(years)
    expect = [
        "pre-2008", "2008-09 crash", "2010-12 peak workout",
        "2013-16 recovery", "2017-19 calm", "2020+ covid-modern",
    ]
    assert list(out.astype(str)) == expect


def test_liq_year_bucket_ordered_categorical():
    out = lgd.liq_year_bucket(pd.Series([2011]))
    assert list(out.categories) == lgd.LIQ_YEAR_BUCKET_ORDER
    assert out.ordered


# ---------------------------------------------------------------------------
# 8. population_lgd_summary: "loss not yet finalized" liquidations must be
#    EXCLUDED from mean_realized_lgd, never zero-filled (a prior version of
#    this function silently treated a missing actual_loss_calculation as a
#    $0 loss, biasing mean_realized_lgd down -- see fit_lgd.py's docstring
#    on population_lgd_summary).
# ---------------------------------------------------------------------------
def test_population_summary_excludes_not_yet_finalized_liquidations(full_sample, full_models):
    pop = fl.population_lgd_summary(full_sample, full_models)
    row = pop.loc[pop["split"] == "train"].iloc[0]

    resolved = full_sample.loc[
        (full_sample["lgd_outcome"] != "unresolved") & (full_sample["split"] == "train")
    ].dropna(subset=["ltv10", "fico_s", "loan_age_at_default", "era", "property_state"])
    liq_no_loss = (resolved["lgd_outcome"] == "liquidation") & ~resolved["has_loss_data"]
    assert int(row["n_liq_excluded_no_loss_data"]) == int(liq_no_loss.sum())
    if liq_no_loss.sum() == 0:
        pytest.skip("this vintage has no 'loss not yet finalized' liquidations to distinguish on")

    # Reconstruct the WRONG zero-filled statistic and confirm the reported
    # mean_realized_lgd is NOT it (they'd coincide only if excluding vs.
    # zero-filling happened to net to the same mean, astronomically unlikely
    # whenever excluded rows exist and severities are nonzero).
    wrong_zero_filled = np.where(
        resolved["lgd_outcome"] == "cure", 0.0, resolved["severity"].fillna(0.0),
    ).mean()
    assert row["mean_realized_lgd"] != pytest.approx(wrong_zero_filled)

    # Correct value: cure -> 0, liquidation-with-loss-data -> severity,
    # liquidation-without-loss-data -> EXCLUDED (not averaged in at all).
    usable = resolved.loc[~liq_no_loss]
    correct = np.where(usable["lgd_outcome"] == "cure", 0.0, usable["severity"]).mean()
    assert row["mean_realized_lgd"] == pytest.approx(correct)
