"""Regenerate Ch.6 (Scenarios, Satellite Models & Jensen's Inequality) figures.

Run: uv run --no-sync python notes/assets/img/ch06/build_diagrams.py

01_scenario_ecl_pipeline.png and 04_coherent_shock_sketch.png are box-arrow
flowcharts (matplotlib, per notes/plan/conventions.md "flowcharts are never
embedded unchecked"). 05_toy_jensen_chord.png redraws the golden-fixture
toy Jensen example (tests/fixtures/compute_scenarios.py) in the project's
house style, matching the visual language of the already-house-style
outputs/scenario_ecl/jensen_gap.png (copied in as 06_jensen_gap.png, not
regenerated, since it is already this project's own matplotlib output).
02/03/06/07 are plain `cp` copies of existing outputs/ PNGs -- see this
directory's git-tracked copies; only 01/04/05 are generated by this script.

Numeric sources, all recomputed here (recipe law -- never hand-typed):
  * tests/fixtures/compute_scenarios.py -- the toy 3-scenario Vasicek/ECL example.
  * agent/tools_tier1.py (_comovement_betas, shock_macro) + outputs/models/
    tier1_models.joblib (warm cache) -- the real +2pp UER coherent-shock chain.
  * outputs/scenario_ecl/scenario_ecl_summary.csv -- the three real per-
    scenario reported allowances used as pipeline-diagram labels.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4] / ".claude/skills/pageindex-plus/assets"))
from matplotlib_setup import apply_textbook_style, COLORS  # noqa: E402

apply_textbook_style()
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch  # noqa: E402
import numpy as np  # noqa: E402
from scipy.stats import norm  # noqa: E402

OUT = Path(__file__).resolve().parent


def box(ax, xy, w, h, text, fc="white", ec=COLORS["accent"], fontsize=8.4,
        textcolor="#1a1a1a", lw=1.3, zorder=3):
    x, y = xy
    p = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.02,rounding_size=0.02",
                        linewidth=lw, edgecolor=ec, facecolor=fc, zorder=zorder)
    ax.add_patch(p)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
             fontsize=fontsize, color=textcolor, zorder=zorder + 1, linespacing=1.35)
    return p


def arrow(ax, p0, p1, color="#555555", lw=1.4, style="-|>",
          connectionstyle="arc3,rad=0.0", ls="-"):
    a = FancyArrowPatch(p0, p1, arrowstyle=style, mutation_scale=13,
                         color=color, lw=lw, linestyle=ls, zorder=2,
                         connectionstyle=connectionstyle, shrinkA=2, shrinkB=2)
    ax.add_patch(a)


# =============================================================================
# Exhibit 6.1 -- scenario -> ECL pipeline (the whole chapter's machinery)
# =============================================================================
def fig_pipeline():
    fig, ax = plt.subplots(figsize=(9.2, 9.6))
    ax.set_xlim(0, 10)
    ax.set_ylim(5.3, 24.5)
    ax.axis("off")

    ax.text(5.0, 24.2,
            "DFAST 2026 supervisory CSVs -> rebased 40q scenario paths -> satellite -> Vasicek PIT -> "
            "frozen ECL engine -> probability-weighted allowance",
            ha="center", va="top", fontsize=8.6, style="italic", color="#4a4a4a")

    # Row 1: DFAST source
    box(ax, (2.4, 22.3), 5.2, 1.25,
        "DFAST 2026 Baseline / Severely-Adverse\n13 quarters, 2026Q1-2029Q1 (§6.2)",
        fc="#f7f5ee", ec=COLORS["gray"], fontsize=8.4)

    # Row 2: three lanes -- deltas
    lane_x = [0.4, 3.6, 6.8]
    lane_w = 2.8
    lane_labels_2 = [
        "UP\ndelta = -0.35 x (severe - jumpoff)\n(damped mirror, §6.3)",
        "BASE\ndelta = baseline - jumpoff",
        "DOWN\ndelta = severe - jumpoff",
    ]
    lane_colors = [COLORS["good"], COLORS["accent"], COLORS["warn"]]
    for x, lbl, c in zip(lane_x, lane_labels_2, lane_colors):
        box(ax, (x, 20.3), lane_w, 1.5, lbl, fc="white", ec=c, fontsize=8.0)
    arrow(ax, (5.0, 22.3), (5.0, 21.9), color=COLORS["gray"])
    for x in lane_x:
        arrow(ax, (5.0, 22.28), (x + lane_w / 2, 21.85), color="#999999", lw=1.0)

    # Row 3: rebase + extend (single wide box, uniform operation)
    box(ax, (1.0, 18.3), 8.0, 1.55,
        "REBASE onto panel t=60 + EXTEND to 40q (§6.2, §6.4)\n"
        "scenario_h = panel_t60_level + delta_h  (h=1..13, the R&S window)\n"
        "h=14..21: linear reversion to panel long-run mean;  h=21..40: hold",
        fc="#eef3fb", ec=COLORS["accent"], fontsize=8.2)
    for x in lane_x:
        arrow(ax, (x + lane_w / 2, 20.3), (5.0, 19.85), color=lane_colors[lane_x.index(x)], lw=1.1)

    # Row 4: satellite
    box(ax, (0.8, 16.3), 8.4, 1.55,
        "SATELLITE (§6.5): Z_h = -1.6942 + 13.6424·hpi_growth_lag1(h) + 0.7302·gdp_growth_lag2(h)\n"
        "one Z path per scenario, h=1..40 (OLS, n=57 quarters, sign-governed)",
        fc="white", ec=COLORS["purple"], fontsize=8.3)
    arrow(ax, (5.0, 18.3), (5.0, 17.85), color=COLORS["accent"])

    # Row 5: Vasicek conditioning
    box(ax, (0.8, 14.3), 8.4, 1.55,
        "VASICEK PIT-CONDITION (Ch.5): λ_PIT(loan, h) = pit_pd(λ_TTC(loan, h), Z_h, ρ=0.0227)\n"
        "applied to the FROZEN default hazard, quarter by quarter; prepay/LGD/EAD unconditioned",
        fc="white", ec=COLORS["purple"], fontsize=8.1)
    arrow(ax, (5.0, 16.3), (5.0, 15.85), color=COLORS["purple"])

    # Row 6: frozen ECL engine
    box(ax, (0.8, 12.3), 8.4, 1.55,
        "FROZEN ECL ENGINE (Ch.2, unmodified): sum_h S(h-1)·λ_h·LGD_h·EAD_h·(1+EIR)^-h\n"
        "per loan, 7,849 exposures, t=60 (2015Q1) reporting date",
        fc="white", ec=COLORS["accent"], fontsize=8.2)
    arrow(ax, (5.0, 14.3), (5.0, 13.85), color=COLORS["purple"])

    # Row 7: three lanes -- per-scenario allowance
    lane_labels_7 = ["UP\n$27.7m\n1.65% cov.", "BASE\n$30.5m\n1.82% cov.",
                     "SEVERE\n$47.6m\n2.84% cov."]
    for x, lbl, c in zip(lane_x, lane_labels_7, lane_colors):
        box(ax, (x, 10.2), lane_w, 1.55, lbl, fc="white", ec=c, fontsize=9.2)
    arrow(ax, (5.0, 12.3), (5.0, 11.9), color=COLORS["accent"])
    for x in lane_x:
        arrow(ax, (5.0, 12.28), (x + lane_w / 2, 11.75), color="#999999", lw=1.0)

    # Row 8: probability weighting
    box(ax, (1.2, 7.9), 7.6, 1.7,
        "PROBABILITY WEIGHT (§6.1, governance): 0.50·BASE + 0.25·DOWN + 0.25·UP\n"
        "-> weighted reported allowance = $34.0m   (THE IFRS 9 §5.5.17 ANSWER)",
        fc="#fff7e6", ec=COLORS["purple"], fontsize=8.6, lw=1.6)
    for x in lane_x:
        arrow(ax, (x + lane_w / 2, 10.2), (5.0, 9.6), color=lane_colors[lane_x.index(x)], lw=1.1)

    # Jensen warning box, off to the side
    box(ax, (1.2, 5.9), 7.6, 1.5,
        "JENSEN CAUTION (§6.7-6.9): weighted allowance $34.0m  >  ECL of the weighted-AVERAGE\n"
        "Z path $32.9m  ->  ratio 1.035x. Never average the paths first and score once.",
        fc="#fdecea", ec=COLORS["warn"], fontsize=8.3, lw=1.4)
    arrow(ax, (5.0, 7.9), (5.0, 7.4), color=COLORS["warn"], ls="--")

    ax.set_title("Exhibit 6.1 -- the scenario-conditional ECL pipeline, DFAST CSV to weighted allowance",
                 fontsize=11)
    fig.tight_layout()
    fig.savefig(OUT / "01_scenario_ecl_pipeline.png")
    plt.close(fig)
    print("wrote 01_scenario_ecl_pipeline.png")


# =============================================================================
# Exhibit 6.4 -- coherent-shock direction sketch (naive vs coherent)
# =============================================================================
def fig_coherent_shock():
    fig, ax = plt.subplots(figsize=(9.4, 8.6))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 13.4)
    ax.axis("off")

    box(ax, (2.6, 12.0), 4.8, 1.1,
        "Agent request: shock UER +2pp (parallel)",
        fc="#f7f5ee", ec=COLORS["gray"], fontsize=8.8)
    arrow(ax, (3.7, 12.0), (2.3, 10.75), color="#888888")
    arrow(ax, (6.3, 12.0), (7.7, 10.75), color="#888888")

    # LEFT lane: naive univariate shock (WRONG)
    ax.text(2.3, 11.25, "naive: UER only", ha="center", fontsize=8.6,
             color=COLORS["warn"], style="italic")
    box(ax, (0.35, 9.2), 3.9, 1.35,
        "hold hpi_growth, gdp_growth\nFIXED at the base path",
        fc="white", ec=COLORS["warn"], fontsize=8.0)
    arrow(ax, (2.3, 9.2), (2.3, 8.05), color=COLORS["warn"])
    box(ax, (0.35, 6.55), 3.9, 1.5,
        "satellite Z_h = f(hpi_growth_lag1, gdp_growth_lag2)\nhas NO uer term -> Z_h UNCHANGED",
        fc="white", ec=COLORS["warn"], fontsize=8.0)
    arrow(ax, (2.3, 6.55), (2.3, 5.4), color=COLORS["warn"])
    box(ax, (0.35, 4.1), 3.9, 1.3,
        "ECL delta = $0.00\n(a UER-only question gets a null answer)",
        fc="#fdecea", ec=COLORS["warn"], fontsize=8.4, lw=1.6)
    ax.text(2.3, 3.75, "X  economically wrong -- coherent supervisory\nscenarios never move one variable alone",
            ha="center", fontsize=7.6, color=COLORS["warn"], style="italic")

    # RIGHT lane: coherent multivariate shock (project's convention)
    ax.text(7.7, 11.25, "coherent: co-moving shock", ha="center", fontsize=8.6,
             color=COLORS["good"], style="italic")
    box(ax, (5.75, 9.05), 3.9, 1.5,
        "co-movement loadings β (severe-minus-base,\n13q R&S window): β[hpi]=-0.00413,\nβ[gdp]=-0.05452 (§6.6)",
        fc="white", ec=COLORS["good"], fontsize=7.8)
    arrow(ax, (7.7, 9.05), (7.7, 7.9), color=COLORS["good"])
    box(ax, (5.75, 6.4), 3.9, 1.5,
        "per-concept deltas, every quarter:\nuer +2.00pp, hpi_growth -0.826pp/q,\ngdp_growth -0.109pp/q",
        fc="white", ec=COLORS["good"], fontsize=7.8)
    arrow(ax, (7.7, 6.4), (7.7, 5.25), color=COLORS["good"])
    box(ax, (5.75, 3.75), 3.9, 1.5,
        "shocked Z path: ΔZ=0 (h=1),\n-0.1127 (h=2), -0.1923 steady\nfrom h=3 (both lags active)",
        fc="white", ec=COLORS["good"], fontsize=7.8)
    arrow(ax, (7.7, 3.75), (7.7, 2.6), color=COLORS["good"])
    box(ax, (5.75, 1.1), 3.9, 1.5,
        "Vasicek PIT -> frozen ECL re-run,\n7,849 loans:\n$30.454m -> $31.694m (+4.1%)",
        fc="#eaf7f1", ec=COLORS["good"], fontsize=8.2, lw=1.6)
    ax.text(7.7, 0.75, "OK  co-movement preserved, DFAST severe-minus-\nbase direction, matches the recorded trace",
            ha="center", fontsize=7.6, color=COLORS["good"], style="italic")

    ax.set_title("Exhibit 6.4 -- the coherent-shock convention: why a UER-only path move cannot reach Z",
                 fontsize=10.6)
    fig.tight_layout()
    fig.savefig(OUT / "04_coherent_shock_sketch.png")
    plt.close(fig)
    print("wrote 04_coherent_shock_sketch.png")


# =============================================================================
# Exhibit 6.5 -- the toy fixture's Jensen chord (compute_scenarios.py numbers)
# =============================================================================
def fig_toy_jensen():
    EAD, LGD, PD_TTC, RHO = 100.0, 0.40, 0.02, 0.12
    G_ANCHOR, G_SCALE = 2.0, 1.5

    def z_of_g(g):
        return (g - G_ANCHOR) / G_SCALE

    def pd_pit(z):
        return norm.cdf((norm.ppf(PD_TTC) - RHO ** 0.5 * z) / (1 - RHO) ** 0.5)

    def ecl_of_z(z):
        return pd_pit(z) * LGD * EAD

    scenarios = {"upside": (+3.5, 0.25, COLORS["good"]),
                 "base": (+2.0, 0.50, COLORS["accent"]),
                 "downside": (-2.5, 0.25, COLORS["warn"])}

    zs = np.linspace(-3.3, 1.3, 400)
    curve = [ecl_of_z(z) for z in zs]

    avg_g = sum(w * g for g, w, _ in scenarios.values())
    avg_z = z_of_g(avg_g)
    avg_path_ecl = ecl_of_z(avg_z)
    weighted_ecl = sum(w * ecl_of_z(z_of_g(g)) for g, w, _ in scenarios.values())

    fig, ax = plt.subplots(figsize=(8.6, 5.2))
    ax.plot(zs, curve, color=COLORS["accent"], lw=2.0,
            label="ECL(Z) = PD_PIT(Z)·LGD·EAD  (toy: PD_TTC=2%, ρ=0.12)")

    for name, (g, w, c) in scenarios.items():
        z = z_of_g(g)
        ax.scatter([z], [ecl_of_z(z)], color=c, s=70, zorder=5, edgecolor="white", linewidth=1)
        ax.annotate(f"{name}\n€{ecl_of_z(z):.2f}m", (z, ecl_of_z(z)),
                    textcoords="offset points", xytext=(10, 8), fontsize=8.2, color=c)

    ax.scatter([avg_z], [weighted_ecl], marker="D", s=110, color=COLORS["purple"],
               zorder=6, edgecolor="white", linewidth=1,
               label=f"probability-weighted ECL = €{weighted_ecl:.2f}m (the IFRS 9 answer)")
    ax.scatter([avg_z], [avg_path_ecl], marker="s", s=90, color=COLORS["orange"],
               zorder=6, edgecolor="white", linewidth=1,
               label=f"ECL at the average path (Z={avg_z:.2f}) = €{avg_path_ecl:.2f}m")
    ax.annotate(f"Jensen gap: {weighted_ecl / avg_path_ecl:.2f}x\n"
                f"(€{weighted_ecl:.2f}m vs €{avg_path_ecl:.2f}m, {100*(1-avg_path_ecl/weighted_ecl):.0f}% understatement)",
                (avg_z, (weighted_ecl + avg_path_ecl) / 2),
                textcoords="offset points", xytext=(14, 0), fontsize=8.6,
                color="#1a1a1a", fontweight="bold")

    ax.set_xlabel("Z (systematic factor)")
    ax.set_ylabel("1-year ECL (€m)")
    ax.set_title("Exhibit 6.5 -- the toy fixture's Jensen gap (tests/fixtures/compute_scenarios.py)")
    ax.legend(loc="upper right", fontsize=7.6, framealpha=0.9)
    fig.tight_layout()
    fig.savefig(OUT / "05_toy_jensen_chord.png")
    plt.close(fig)
    print("wrote 05_toy_jensen_chord.png "
          f"(weighted={weighted_ecl:.4f}, avg_path={avg_path_ecl:.4f}, "
          f"ratio={weighted_ecl / avg_path_ecl:.4f})")


if __name__ == "__main__":
    fig_pipeline()
    fig_coherent_shock()
    fig_toy_jensen()
